dist: bionic
language: c
services:
  - docker
compiler:
  - gcc
  - clang
before_script:
  - sudo apt-get update
script:
  - (./install-linux.sh && make tests)
after_failure:
  - cat build/Testing/Temporary/LastTest.log
