name: 'NGS'
description: 'Next Generation Shell (NGS)'
branding:
  icon: 'award'
  color: 'purple'
runs:
  using: "composite"
  steps:
    - name: Install
      run: |
        echo "GITHUB_ACTION_PATH=$GITHUB_ACTION_PATH"
        cd $GITHUB_ACTION_PATH
        ./install.sh
      shell: bash