name: Build
on: push

jobs:
  build-internal-apt-gcc:
    timeout-minutes: 5
    name: Build in GCC
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ "ubuntu-20.04" ]
        version: [ "9", "10", "11" ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y g++-${{ matrix.version }}
          echo "CC=gcc-${{ matrix.version }}" >> $GITHUB_ENV
          echo "CXX=g++-${{ matrix.version }}" >> $GITHUB_ENV
      - name: Install and Test
        run: (./install.sh && make tests)

  build-internal-apt-clang:
    timeout-minutes: 5
    name: Build in Clang
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ "ubuntu-20.04" ]
        version: [ "9", "10", "11" ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-${{ matrix.version }}
          echo "CC=clang-${{ matrix.version }}" >> $GITHUB_ENV
          echo "CXX=clang++-${{ matrix.version }}" >> $GITHUB_ENV
      - name: Install and Test
        run: (./install.sh && make tests)

  build-external-apt-gcc:
    timeout-minutes: 5
    name: Build in GCC
    runs-on: ubuntu-20.04
    container:
      image: ${{ matrix.container }}
      options: --user root
    strategy:
      matrix:
        container: [ "debian:11.1" ]
        version: [ "9", "10" ] # gcc 11 doesn't exist in debian apt
    steps:
      - uses: actions/checkout@v2
      - name: Setup Compiler
        run: |
          apt-get update
          apt-get install -y g++-${{ matrix.version }}
          echo "CC=gcc-${{ matrix.version }}" >> $GITHUB_ENV
          echo "CXX=g++-${{ matrix.version }}" >> $GITHUB_ENV
      - name: Install and Test
        run: (./install.sh && make tests)

  build-external-apt-clang:
    timeout-minutes: 5
    name: Build in Clang
    runs-on: ubuntu-20.04
    container:
      image: ${{ matrix.container }}
      options: --user root
    strategy:
      matrix:
        container: [ "debian:11.1" ]
        version: [ "9", "11" ] # clang 10 doesn't exist in debian apt
    steps:
      - uses: actions/checkout@v2
      - name: Setup Compiler
        run: |
          apt-get update
          apt-get install -y clang-${{ matrix.version }}
          echo "CC=clang-${{ matrix.version }}" >> $GITHUB_ENV
          echo "CXX=clang++-${{ matrix.version }}" >> $GITHUB_ENV
      - name: Install and Test
        run: (./install.sh && make tests)

  build-external-yum-gcc:
    timeout-minutes: 10
    name: Build in default GCC
    runs-on: ubuntu-20.04
    container:
      image: ${{ matrix.container }}
      options: --user root
    strategy:
      matrix:
        container: [ "fedora:34", "fedora:35", "amazonlinux:2", 'centos:8' ]
    steps:
      - name: Install AmazonLinux Deps
        if: startsWith(matrix.container, 'amazonlinux')
        run: yum -y install tar xz gzip
      - name: Install CentOS Deps
        if: startsWith(matrix.container, 'centos:8')
        run: |
          yum -y install epel-release dnf-plugins-core
          yum config-manager --set-enabled powertools
      - uses: actions/checkout@v2
      - name: Setup Compiler
        run: |
          yum -y install sudo gcc-c++
          echo "CC=gcc" >> $GITHUB_ENV
          echo "CXX=g++" >> $GITHUB_ENV
      - name: Install and Test
        run: (./install.sh && make tests)

  build-external-yum-clang:
    timeout-minutes: 10
    name: Build in default Clang
    runs-on: ubuntu-20.04
    container:
      image: ${{ matrix.container }}
      options: --user root
    strategy:
      matrix:
        container: [ "fedora:34", "fedora:35", "amazonlinux:2", "centos:8" ]
    steps:
      - name: Install AmazonLinux Deps
        if: startsWith(matrix.container, 'amazonlinux')
        run: yum -y install tar xz gzip
      - name: Install CentOS Deps
        if: startsWith(matrix.container, 'centos:8')
        run: |
          yum -y install epel-release dnf-plugins-core
          yum config-manager --set-enabled powertools
      - uses: actions/checkout@v2
      - name: Setup Compiler
        run: |
          yum -y install sudo clang
          echo "CC=clang" >> $GITHUB_ENV
          echo "CXX=clang++" >> $GITHUB_ENV
      - name: Install and Test
        run: (./install.sh && make tests)

  build-external-centos8-gcc:
    timeout-minutes: 10
    name: Build in GCC
    runs-on: ubuntu-20.04
    container:
      image: ${{ matrix.container }}
      options: --user root
    strategy:
      matrix:
        container: [ "centos:8" ]
        version: [ "9", "10", "11" ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Compiler
        run: |
          yum -y install epel-release dnf-plugins-core sudo
          yum config-manager --set-enabled powertools
          yum -y install gcc-toolset-${{ matrix.version }}-gcc-c++
          source /opt/rh/gcc-toolset-${{ matrix.version }}/enable
      - name: Install and Test
        run: (source /opt/rh/gcc-toolset-${{ matrix.version }}/enable && ./install.sh && make tests)

  build-external-centos7-gcc:
    timeout-minutes: 10
    name: Build in GCC
    runs-on: ubuntu-20.04
    container:
      image: ${{ matrix.container }}
      options: --user root
    strategy:
      matrix:
        container: [ "centos:7" ]
        version: [ "9", "10", "11" ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Compiler
        run: |
          yum -y install centos-release-scl epel-release sudo
          yum -y install devtoolset-${{ matrix.version }}
          source /opt/rh/devtoolset-${{ matrix.version }}/enable
      - name: Install and Test
        run: (source /opt/rh/devtoolset-${{ matrix.version }}/enable && ./install.sh && make tests)

  build-mac-gcc:
    timeout-minutes: 10
    name: Build in GCC
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ "macOS-10.15" ]
        version: [ "9", "10", "11" ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Compiler
        run: |
          brew install cmake ninja
          brew install gcc@${{ matrix.version }}
          echo "CC=gcc-${{ matrix.version }}" >> $GITHUB_ENV
          echo "CXX=g++-${{ matrix.version }}" >> $GITHUB_ENV
      - name: Install and Test
        run: (./install.sh && make tests)

  build-mac-xcode:
    timeout-minutes: 15
    name: Build in Xcode
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ "macOS-10.15" ]
        version: [ "10.3" ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Compiler
        run: |
          brew install cmake ninja
          sudo xcode-select -switch /Applications/Xcode_${{ matrix.version }}.app
          echo "CC=clang" >> $GITHUB_ENV
          echo "CXX=clang++" >> $GITHUB_ENV
      - name: Install and Test
        run: (./install.sh && make tests)
