name: Build
on: push

jobs:
  build-linux-internal-gcc:
    timeout-minutes: 5
    name: Build in GCC
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ "ubuntu-20.04" ]
        version: [ "9", "10" ]
    steps:
      - uses: actions/checkout@v2
      - name: Install Compiler (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y g++-${{ matrix.version }}
          echo "CC=gcc-${{ matrix.version }}" >> $GITHUB_ENV
          echo "CXX=g++-${{ matrix.version }}" >> $GITHUB_ENV
      - name: Install and Test
        run: (./install.sh && make tests)

  build-linux-internal-clang:
    timeout-minutes: 5
    name: Build in Clang
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ "ubuntu-20.04" ]
        version: [ "9", "10" ]
    steps:
      - uses: actions/checkout@v2
      - name: Install Compiler (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-${{ matrix.version }}
          echo "CC=clang-${{ matrix.version }}" >> $GITHUB_ENV
          echo "CXX=clang++-${{ matrix.version }}" >> $GITHUB_ENV
      - name: Install and Test
        run: (./install.sh && make tests)

  build-linux-external-gcc:
    timeout-minutes: 5
    name: Build in GCC
    runs-on: ubuntu-20.04
    container:
      image: ${{ matrix.container }}
      options: --user root
    strategy:
      matrix:
        container: [ "debian:11.1" ]
        version: [ "9", "10" ]
    steps:
      - uses: actions/checkout@v2
      - name: Install Compiler
        run: |
          apt-get update
          apt-get install -y g++-${{ matrix.version }}
          echo "CC=gcc-${{ matrix.version }}" >> $GITHUB_ENV
          echo "CXX=g++-${{ matrix.version }}" >> $GITHUB_ENV
      - name: Install and Test
        run: (./install.sh && make tests)

  build-linux-external-clang:
    timeout-minutes: 5
    name: Build in Clang
    runs-on: ubuntu-20.04
    container:
      image: ${{ matrix.container }}
      options: --user root
    strategy:
      matrix:
        container: [ "debian:11.1" ]
        version: [ "9", "11" ]
    steps:
      - uses: actions/checkout@v2
      - name: Install Compiler
        run: |
          apt-get update
          apt-get install -y clang-${{ matrix.version }}
          echo "CC=clang-${{ matrix.version }}" >> $GITHUB_ENV
          echo "CXX=clang++-${{ matrix.version }}" >> $GITHUB_ENV
      - name: Install and Test
        run: (./install.sh && make tests)

  build-mac-gcc:
    timeout-minutes: 5
    name: Build in GCC
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ "macOS-10.14" ]
        version: [ "9" ]
    steps:
      - uses: actions/checkout@v2
      - name: Install Compiler (macOS)
        run: |
          brew install cmake ninja
          brew install gcc@${{ matrix.version }}
          echo "CC=gcc-${{ matrix.version }}" >> $GITHUB_ENV
          echo "CXX=g++-${{ matrix.version }}" >> $GITHUB_ENV
      - name: Install and Test
        run: (./install.sh && make tests)

  build-mac-xcode:
    timeout-minutes: 15
    name: Build in Xcode
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ "macOS-10.14" ]
        version: [ "10.3" ]
    steps:
      - uses: actions/checkout@v2
      - name: Install Compiler (macOS)
        run: |
          brew install cmake ninja
          sudo xcode-select -switch /Applications/Xcode_${{ matrix.version }}.app
          echo "CC=clang" >> $GITHUB_ENV
          echo "CXX=clang++" >> $GITHUB_ENV
      - name: Install and Test
        run: (./install.sh && make tests)
