name: Release Snap
on:
  release:
    types:
      - created
    tags:
      - v*

jobs:
  release:
    timeout-minutes: 15
    name: Release Snap
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Updating version.h and snap/snapcraft.yaml with version
        run: |
          VERSION=${GITHUB_REF##*/v} && echo $VERSION
          sed -i "s/#define NGS_VERSION \".*\"/#define NGS_VERSION \"$VERSION\"/" version.h
          sed -i "s/version: '.*'/version: '$VERSION'/" snap/snapcraft.yaml
          sed -i "s/grade: .*/grade: stable/" snap/snapcraft.yaml
      - name: NGS - Install and Test
        run: (./install.sh && make tests)
      - name: SNAP - Build
        uses: snapcore/action-build@v1
        id: build-snap
      - name: SNAP - Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: snap
          path: ${{ steps.build-snap.outputs.snap }}
      - name: SNAP - Publish to store
        uses: snapcore/action-publish@v1
        with:
          store_login: ${{ secrets.SNAP_LOGIN }}
          snap: ${{ steps.build-snap.outputs.snap }}
